development:
  adapter: postgresql
  encoding: unicode
  database: alienvspred_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: alienvspred_production
  pool: 5
  username: postgres
  password:
