development:
  adapter: postgresql
  encoding: unicode
  database: helium_development
  pool: 5
  host: localhost
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: helium_production
  pool: 5
  host: localhost
  username: postgres
  password:
